/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type EinsatzStats = {
  _id: string;
  _type: 'einsatzStats';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  year?: number;
  ff?: number;
  fr?: number;
};

export type Einsatz = {
  _id: string;
  _type: 'einsatz';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  locality?: string;
  date?: string;
  category?: 'Besondere Eins\xE4tze' | 'Br\xE4nde' | 'First Responder THL' | 'Sicherheitswache' | 'THL' | '\xDCbungen / Lehrg\xE4nge / Veranstaltungen' | 'Verkehrsabsicherung' | 'Wasserdienst';
  incident?: number;
  slug?: Slug;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Info = {
  _id: string;
  _type: 'info';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  message?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  index?: number;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | EinsatzStats
  | Einsatz
  | Slug
  | Info
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./lib/InfoService.ts
// Variable: INFO_QUERY
// Query: *[_type == "info"]{ _id, title, message, index }
export type INFO_QUERYResult = Array<{
  _id: string;
  title: string | null;
  message: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  index: number | null;
}>;

// Source: ./lib/OperationService.ts
// Variable: OPERATION_QUERY
// Query: *[_type == "einsatz"]{ _id, title, locality, date, category, incident, slug }
export type OPERATION_QUERYResult = Array<{
  _id: string;
  title: string | null;
  locality: string | null;
  date: string | null;
  category: 'Besondere Eins\xE4tze' | 'Br\xE4nde' | 'First Responder THL' | 'Sicherheitswache' | 'THL' | '\xDCbungen / Lehrg\xE4nge / Veranstaltungen' | 'Verkehrsabsicherung' | 'Wasserdienst' | null;
  incident: number | null;
  slug: Slug | null;
}>;

// Source: ./lib/OperationStatsService.ts
// Variable: OPERATION_STATS_QUERY
// Query: *[_type == "einsatzStats"]{ _id, year, ff, fr }
export type OPERATION_STATS_QUERYResult = Array<{
  _id: string;
  year: number | null;
  ff: number | null;
  fr: number | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "info"]{ _id, title, message, index }': INFO_QUERYResult;
    '*[_type == "einsatz"]{ _id, title, locality, date, category, incident, slug }': OPERATION_QUERYResult;
    '*[_type == "einsatzStats"]{ _id, year, ff, fr }': OPERATION_STATS_QUERYResult;
  }
}
